import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'
 


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const cormorant = localFont({
  src: '../../public/fonts/Cormorant.ttf',
}); 

export const dancing = localFont({
  src: "../../public/fonts/Dancing.ttf",
});

export const epunda = localFont({
  src: "../../public/fonts/EpundaSlab.ttf",
});

export const karla = localFont({
  src: "../../public/fonts/Karla.ttf",
});

export const roboto = localFont({
  src: "../../public/fonts/Roboto.ttf",
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${cormorant.className} ${dancing.className} ${epunda.className} ${karla.className} ${roboto.className}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
